# Foreground Colors
export DEFAULT="\e[39m"
export BLACK="\e[30m"
export RED="\e[31m"
export GREEN="\e[32m"
export YELLOW="\e[33m"
export BLUE="\e[34m"
export MAGENTA="\e[35m"
export CYAN="\e[36m"
export LGRAY="\e[37m"
export LRED="\e[91m"
export LGREEN="\e[92m"
export LYELLOW="\e[93m"
export LBLUE="\e[94m"
export LMAGENTA="\e[95m"
export LCYAN="\e[96m"
export WHITE="\e[97m"

# Styles
export BOLD="\e[01m"
export NORMAL="\e[00m"
export CURSIVE="\e[03m"
export UNDERLINED="\e[04m"
export BLINKING="\e[05m"
export STRIKETHROUGH="\e[09m"

# Background Colors
export BGDEFAULT="\e[49m"
export BGBLACK="\e[40m"
export BGRED="\e[41m"
export BGGREEN="\e[42m"
export BGYELLOW="\e[43m"
export BGBLUE="\e[44m"
export BGMAGENTA="\e[45m"
export BGCYAN="\e[46m"
export BGLGRAY="\e[47m"
export BGWHITE="\e[07m"
